language: python
python:
  - 3.6
env:
  matrix:
    - NODE_VER=latest
    - NODE_VER=lts
    - GROUP=node
sudo: false
cache:
  pip: true
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
install:
  - npm install
script:
  - npm run test:cov
after_success:
  - codecov
