language: node_js
node_js:
  - "node"
  - "lts/*"
sudo: false
cache:
  pip: true
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
install:
  - npm install
script:
  - npm run test:cov
after_success:
  - codecov
