language: python
python:
  - 3.6
env:
  matrix:
    - NODE_VER=latest
    - NODE_VER=lts/*
sudo: false
cache:
  pip: true
  directories:
    - node_modules # NPM packages
    - $HOME/.npm
install:
  - pip install ipywidgets
  - nvm install '$NODE_VER'
  - npm install
script:
  - npm run test:cov
after_success:
  - codecov
